./run.sh 2vq2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a0l /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 2ho1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2c2l /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3ebb /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 4cr4 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2xev /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3asd /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3u4t /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2uy1 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2kq5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2qk2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3si5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6n88 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5d80 /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 2xq0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ukl /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 6fc4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ios /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2x19 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a1g /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2q7f /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a0l /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 3esl /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1tr4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3fga /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1gw6 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5ohu /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2yjy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2x1g /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 3mdj /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2n3u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cv5 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3gz1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3jxz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ib2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xpy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xev /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5jjo /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1g3n /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1k3z /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3nby /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 4i9e /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5a31 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2xpi /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 6fcs /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3woy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cr2 /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 1h6k /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1s70 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5l9u /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4qmi /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1bk5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5khr /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 3jcp /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 3bvs /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3n6s /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2vgx /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1sly /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a1g /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1t06 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ug3 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a63 /home/layla/Predictor2/pid_3/ L chain False False > resultsoles 2>error2
./run.sh 2npp /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 3jco /home/layla/Predictor2/pid_3/ N chain False False > resultsoles 2>error2
./run.sh 2a5u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1got /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2vgx /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1z5h /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1upk /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ft1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6ghm /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 5gjr /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 1y8m /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1f59 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gae /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5yfp /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 1klx /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1e96 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4buj /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 4cr2 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 1n54 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
error  

./run.sh 2n3v /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1u6g /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4buj /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4hos /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2uy1 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1e8z /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1bd8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2kzt /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3mvb /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4i1a /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4eba /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3edt /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2pfv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4rl5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4qmi /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1w3b /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xev /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2q7f /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cru /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3txn /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gb8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2n3u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2h4m /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gq2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4zj7 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2b1e /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3ceq /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1e90 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a63 /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 1ycs /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2kcl /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cr4 /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 3w3v /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1m8y /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1wy6 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6q6g /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4qmi /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1bk6 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 3jy1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3jx7 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6fcu /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3zgq /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ho8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cj9 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fp9 /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 1gg2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4g3a /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xpz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1pc2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5cky /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 5l9t /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 2lsu /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3w3u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2x1g /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 1m8x /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2n3w /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ldj /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3jck /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 5vox /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2pqr /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5d0q /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 5l9t /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 3fex /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ios /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a1g /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2b7m /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1m8w /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1a0r /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a0c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3pe3 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1dce /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1jcs /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4gjp /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2iol /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3gz1 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2ho1 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a63 /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 2x1g /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 1fch /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5a9q /home/layla/Predictor2/pid_3/ J chain False False > resultsoles 2>error2
./run.sh 3u3w /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2yd0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2wtk /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 5fjy /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1hh8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2r5s /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5ohu /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2qfc /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3jco /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 3mdj /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3gz2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3nbz /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 1m8y /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1h6k /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2wtk /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gae /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4cr3 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 1ft2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2lsv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3a6p /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 6n88 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a0c /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 5ks5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2iol /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3jcp /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 4gg4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3ulq /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ie3 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gjx /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2b7m /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 1ee4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4k92 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2bku /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2qfc /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1yyh /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2r59 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4k92 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3jcp /home/layla/Predictor2/pid_3/ N chain False False > resultsoles 2>error2
./run.sh 6q6g /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4cr3 /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 1ot8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2pf4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ihg /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2yjy /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5d80 /home/layla/Predictor2/pid_3/ h chain False False > resultsoles 2>error2
./run.sh 4k92 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1qym /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2qfc /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1h2u /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4wzr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3u4t /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2pft /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3w3x /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4j0u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1gp2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5b26 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2b7m /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2fv2 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 4ady /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fsc /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 1h2t /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1kt0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3pe3 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3ebb /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3tgo /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5khu /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 1iip /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5khr /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 5co0 /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4hos /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1h2v /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 5g05 /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 2b6c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3l3f /home/layla/Predictor2/pid_3/ X chain False False > resultsoles 2>error2
./run.sh 3gq2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1dcq /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2dwz /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2yd0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gz2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1p5q /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2xpy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gni /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1qsa /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1e7u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3gyz /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3ebb /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 1utc /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4gjp /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6fcr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2r5s /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5g04 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2h4m /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2vgx /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2hye /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1e7v /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ie4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5fjy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ho1 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1nfi /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 2uwj /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 4gjr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2fv2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4j0u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6fcu /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2vgx /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5a9q /home/layla/Predictor2/pid_3/ a chain False False > resultsoles 2>error2
./run.sh 1jcq /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4crv /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2xpi /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4eba /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4i9c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1blx /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3as4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ie3 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1w3b /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2ie4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2p58 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1ap7 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2fv2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5ks5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3grl /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1erj /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1bi8 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5ekq /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2wvi /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5jjo /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3w3w /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3zjy /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3ma5 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3zkv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3jco /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 3hym /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2r5s /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1c9i /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5bw9 /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 4rl5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 3ebb /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ N chain False False > resultsoles 2>error2
./run.sh 2r59 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2a4z /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1qte /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2dwz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1z3h /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1dce /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2b7m /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3q15 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 6fcr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4k92 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5l9u /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 3w3t /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5l4k /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 6fec /home/layla/Predictor2/pid_3/ 8 chain False False > resultsoles 2>error2
./run.sh 4cj9 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2iol /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3ma5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1wdy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1oyz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5a5b /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 5gjr /home/layla/Predictor2/pid_3/ 3 chain False False > resultsoles 2>error2
./run.sh 2c2l /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 4eba /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a1g /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2ion /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ee5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5bw9 /home/layla/Predictor2/pid_3/ h chain False False > resultsoles 2>error2
./run.sh 2ion /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fhn /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2x19 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5a9q /home/layla/Predictor2/pid_3/ S chain False False > resultsoles 2>error2
./run.sh 1bk6 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4gyo /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2db0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5g04 /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 2lah /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ihb /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1mx2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1nzn /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5ljo /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3jcp /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 1h2u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4i9e /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cr3 /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 1b3u /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3j47 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2lah /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1awc /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4bwr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 3uux /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3j9v /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2ggf /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ixv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ N chain False False > resultsoles 2>error2
./run.sh 3asg /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5b26 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3esl /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1oy3 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 4fp9 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3b7r /home/layla/Predictor2/pid_3/ L chain False False > resultsoles 2>error2
./run.sh 3qnf /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2x1g /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 3ibv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2vgy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1z5h /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2kq5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xpi /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2iae /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3q15 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1bi8 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 5vox /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 1qz2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1k1a /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1qz2 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1bpo /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1c9l /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3nby /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1d8e /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1sqm /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1e8w /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1lrv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3hym /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 3gjx /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3u3w /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3asg /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3hym /home/layla/Predictor2/pid_3/ J chain False False > resultsoles 2>error2
./run.sh 1ug3 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1bk5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4cr4 /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 3hym /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a63 /home/layla/Predictor2/pid_3/ J chain False False > resultsoles 2>error2
./run.sh 3jck /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2lsv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a0c /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 6fbt /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1jcr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1m8x /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3m1i /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 4gq2 /home/layla/Predictor2/pid_3/ M chain False False > resultsoles 2>error2
./run.sh 1n52 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1erj /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ot8 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3zhp /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2xpz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3zfw /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5gjq /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 2fi7 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4fhm /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4ct6 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5a31 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 4hot /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3ma5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1u6g /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1hs6 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5d0o /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2fv2 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3nc0 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 5gjq /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 2kzt /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1b3u /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5ayw /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2kcv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1uoh /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fhn /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 4gyo /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5g05 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1gcj /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4e6h /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2qmr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5h2v /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2uy1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5b26 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2xq0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xwu /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1t06 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2r5s /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4wzr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1myo /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3as5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3si5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5voy /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2ypf /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1p5q /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1upl /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4qmj /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2f8x /home/layla/Predictor2/pid_3/ K chain False False > resultsoles 2>error2
./run.sh 1k1b /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1m8w /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1wa5 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2kzt /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3ceq /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3ash /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3zhp /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2c2l /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1z1w /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1wm5 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5mc6 /home/layla/Predictor2/pid_3/ i chain False False > resultsoles 2>error2
./run.sh 3w3z /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5gjr /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 5gjq /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 4i9c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2bku /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2pqr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3nbz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1bpo /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4cr2 /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 3rjv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ukl /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1sw6 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3zjy /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 1fpp /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xev /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5b26 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fsc /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2n3t /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3w3y /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3pst /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1h19 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1a17 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xev /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ouv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2iae /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 2iae /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 5lcw /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 1sw6 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1bu9 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1qz2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4hor /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3jxy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5yfp /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 2pf4 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5khu /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 4i9e /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4i9e /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2kzt /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 6fec /home/layla/Predictor2/pid_3/ 8 chain False False > resultsoles 2>error2
./run.sh 1b9y /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1h6k /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3zjy /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 2npp /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4fsc /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1fch /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a0c /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4qmj /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ihb /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1p5q /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2nbw /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1yyh /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3q7j /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1n11 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5gjr /home/layla/Predictor2/pid_3/ 4 chain False False > resultsoles 2>error2
./run.sh 2n3t /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1kt1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1w9c /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2iol /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2qmr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3nc0 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5a5t /home/layla/Predictor2/pid_3/ M chain False False > resultsoles 2>error2
./run.sh 4eba /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 4cv5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3nmz /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3zfw /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1d8d /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1gxr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5voy /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2pl2 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3q7j /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2wtk /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5crj /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 1ikn /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 1hu3 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4i1a /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4a63 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4qmh /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ejy /home/layla/Predictor2/pid_3/ I chain False False > resultsoles 2>error2
./run.sh 2xwu /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4i1a /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4fp9 /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 5ftp /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1elr /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2vq2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4ct7 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1g3n /home/layla/Predictor2/pid_3/ F chain False False > resultsoles 2>error2
./run.sh 1a0r /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5g04 /home/layla/Predictor2/pid_3/ N chain False False > resultsoles 2>error2
./run.sh 3hym /home/layla/Predictor2/pid_3/ L chain False False > resultsoles 2>error2
./run.sh 3nmz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3q5m /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2lsu /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ee4 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4e85 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3jco /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 5gjq /home/layla/Predictor2/pid_3/ N chain False False > resultsoles 2>error2
./run.sh 2yjy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1bpo /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3a6p /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2w3c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2kcl /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1b9x /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2ot8 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5g04 /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 2c0l /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1e8y /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1ejl /home/layla/Predictor2/pid_3/ I chain False False > resultsoles 2>error2
./run.sh 2fi7 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4hot /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1utc /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1erj /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3psp /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2wtk /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 4a63 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3ugm /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2uy1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xev /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 5a31 /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 1w9c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1he8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2hm8 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4i1a /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 1z3h /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6ghm /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3ks2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2kcv /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1m8z /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2w3c /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2qk2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4qmi /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2pf4 /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 1c9l /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4g3a /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5mc6 /home/layla/Predictor2/pid_3/ i chain False False > resultsoles 2>error2
./run.sh 1qbk /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5lcw /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 3j9t /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 4rl5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2pl2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1upl /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5d0q /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 5a5b /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 2pf4 /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 6fc4 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fsc /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2dvw /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4ui9 /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 2uwj /home/layla/Predictor2/pid_3/ G chain False False > resultsoles 2>error2
./run.sh 4qmh /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4hoq /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5ljo /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 4wzr /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2hye /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 3tgo /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5a5b /home/layla/Predictor2/pid_3/ Q chain False False > resultsoles 2>error2
./run.sh 2wvi /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2iae /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2l6j /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1e8x /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2db0 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 2pqn /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2c2l /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3l9t /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3zn3 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5gjr /home/layla/Predictor2/pid_3/ 1 chain False False > resultsoles 2>error2
./run.sh 5a9q /home/layla/Predictor2/pid_3/ 1 chain False False > resultsoles 2>error2
./run.sh 3gyz /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 5l4k /home/layla/Predictor2/pid_3/ Z chain False False > resultsoles 2>error2
./run.sh 1c9i /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 3as5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4e85 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 6fcs /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4eba /home/layla/Predictor2/pid_3/ C chain False False > resultsoles 2>error2
./run.sh 2ho1 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3hym /home/layla/Predictor2/pid_3/ H chain False False > resultsoles 2>error2
./run.sh 2l6j /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 1mx2 /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 3ash /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 4a0k /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4wzw /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2xpi /home/layla/Predictor2/pid_3/ D chain False False > resultsoles 2>error2
./run.sh 3j9u /home/layla/Predictor2/pid_3/ P chain False False > resultsoles 2>error2
./run.sh 4rl5 /home/layla/Predictor2/pid_3/ B chain False False > resultsoles 2>error2
./run.sh 5ftp /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 6fbt /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 4fp9 /home/layla/Predictor2/pid_3/ E chain False False > resultsoles 2>error2
./run.sh 3mva /home/layla/Predictor2/pid_3/ O chain False False > resultsoles 2>error2
./run.sh 3txm /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
./run.sh 2vgy /home/layla/Predictor2/pid_3/ A chain False False > resultsoles 2>error2
